# Generated by Django 5.2.17 on 2026-08-15 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage_adjustment', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'percentage_adjustment'), name='unique_pricing_profile_name_adjustment')],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='pricing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='machines.pricingprofile'),
        ),
        migrations.CreateModel(
            name='MachinePriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_adjustment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='machines.machine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_price_overrides', to='inventory.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('machine', 'product'), name='unique_machine_product_price_override')],
            },
        ),
    ]
