# Generated by Django 5.2.17 on 2026-08-21 15:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_pricingprofile_machine_pricing_profile_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricingprofile',
            name='unique_pricing_profile_name_adjustment',
        ),
        migrations.AddConstraint(
            model_name='pricingprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('percentage_adjustment'), name='unique_pricing_profile_name_adjustment_ci', violation_error_message='Ya existe una tarifa con el mismo nombre y la misma variación.'),
        ),
    ]
