# Generated by Django 5.2.17 on 2026-08-30 10:42

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('machines', '0003_remove_pricingprofile_unique_pricing_profile_name_adjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineLayoutActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateTimeField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='machines.machinelayout')),
            ],
            options={
                'ordering': ['effective_from', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MachinePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='machines.machinelayout')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_positions', to='inventory.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='machinelayout',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('machine'), name='unique_machine_layout_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='machineposition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('identifier'), models.F('layout'), name='unique_layout_position_identifier_ci'),
        ),
    ]
