# Generated by Django 5.2.17 on 2026-08-30 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_machinelayout_machinelayoutactivation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='columns',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='machine',
            name='rows',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='machinelayout',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('REGISTERED', 'Registrada')], default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='machineposition',
            name='column',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='machineposition',
            name='height',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='machineposition',
            name='row',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='machineposition',
            name='width',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('columns__isnull', True), ('rows__isnull', True)), models.Q(('columns__isnull', False), ('rows__isnull', False)), _connector='OR'), name='machine_grid_dimensions_both_set_or_null'),
        ),
    ]
