# Generated by Django 5.2.17 on 2026-08-30 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_machine_columns_machine_rows_machinelayout_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineposition',
            name='column',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='machineposition',
            name='row',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
