# Generated by Django 5.2.17 on 2026-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_alter_machineposition_column_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinelayoutactivation',
            options={'ordering': ['-effective_from', '-pk']},
        ),
        migrations.AddField(
            model_name='machinelayoutactivation',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinelayoutactivation',
            name='effective_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
