# Generated by Django 5.2.17 on 2026-09-22 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_alter_machinelayoutactivation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinepriceoverride',
            name='percentage_adjustment',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(-100)]),
        ),
        migrations.AlterField(
            model_name='pricingprofile',
            name='percentage_adjustment',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(-100)]),
        ),
    ]
