sonar.projectKey=LWH9900_tfg-vending
sonar.organization=lwh9900

sonar.python.version=3.13

sonar.sources=inventory,machines,purchases,replenishments,sales,dashboard
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/tests/**,**/tests.py

sonar.tests=inventory,machines,purchases,replenishments,sales,dashboard
sonar.test.inclusions=**/tests/**,**/tests.py

sonar.python.coverage.reportPaths=coverage.xml