# Generated by Django 5.2.17 on 2026-08-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_line_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_excl_vat__gte', 0)), name='purchase_line_price_gte_0'),
        ),
    ]
