# Generated by Django 5.2.17 on 2026-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchases', '0002_purchaseline_purchase_line_quantity_gt_0_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.UniqueConstraint(fields=('purchase', 'product'), name='unique_product_per_purchase'),
        ),
    ]
