# Generated by Django 5.2.17 on 2026-08-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseline_unique_product_per_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('REGISTERED', 'Registrada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20),
        ),
    ]
