# Generated by Django 5.2.17 on 2026-08-25 09:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('machines', '0003_remove_pricingprofile_unique_pricing_profile_name_adjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replenished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishments', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ReplenishmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_lines', to='inventory.product')),
                ('replenishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='replenishments.replenishment')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='replenishment_line_quantity_gt_0'), models.UniqueConstraint(fields=('replenishment', 'product'), name='unique_product_per_replenishment')],
            },
        ),
    ]
