# Generated by Django 5.2.17 on 2026-08-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('REGISTERED', 'Registrada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20),
        ),
    ]
