# Generated by Django 5.2.17 on 2026-09-03 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('machines', '0007_alter_machinelayoutactivation_options_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='conflicts_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conflicting_sales', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payload_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.CharField(choices=[('telemetry', 'Telemetría'), ('manual', 'Manual')], default='telemetry', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='voided_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='selection',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('resolved', 'Resuelta'), ('conflict', 'En conflicto'), ('rejected', 'Descartada'), ('voided', 'Anulada')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'telemetry')), fields=('event_id', 'payload_hash'), name='unique_telemetry_event_payload'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('event_id__isnull', False), ('status', 'resolved')), fields=('event_id',), name='unique_resolved_sale_per_event'),
        ),
    ]
