# Generated by Django 5.2.17 on 2026-09-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_alter_machinelayoutactivation_options_and_more'),
        ('sales', '0002_sale_conflicts_with_sale_payload_hash_sale_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='resolution_layout',
            field=models.ForeignKey(blank=True, editable=False, help_text='Disposición utilizada manualmente como referencia para resolver la venta cuando no existía una disposición histórica exacta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_resolved_using_layout', to='machines.machinelayout'),
        ),
    ]
